[vectorfield.fourvortices]
src = [0, 0]
dst = [6, 2]
xlim = [0, 6]
ylim = [-1, 6]
travel_stw = 1

[land]
water_level = [0.9, 0.8, 0.7]
resolution = [3, 4, 5]
random_seed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
penalty = [100]
penalty_init = [0]
penalty_increment = [1]
maxfevals = [5]
outbounds_is_land = [false]

[optimizer.cmaes]
popsize = [500]
L = [200]
num_pieces = [1]
K = [9]
sigma0 = [2]
tolfun = [1e-3]
damping = [1.0]
maxfevals = [500000]

[refiner.fms]
tolfun = [1e-6]
damping = [0.5]
maxfevals = [500000]
